import type { TeamMember } from '../types/teamMember';

export const TEAM_MEMBERS: TeamMember[] = [
  {
    name: 'Artem Stadnik',
    position: 'Tech Lead',
    descriptionKey: 'team.artem_stadnik',
    initials: 'AS',
    gradient: 'from-violet-500 to-indigo-600',
    telegram: 'https://t.me/stadnika',
    email: 'mailto:artem.stadnik.contact@gmail.com',
    github: 'https://github.com/artemstadnik',
    linkedin: 'https://linkedin.com/in/artem-stadnik/',
  },
  {
    name: 'Artem Yurin',
    position: 'Project Manager',
    descriptionKey: 'team.artem_yurin',
    initials: 'AY',
    gradient: 'from-sky-500 to-cyan-600',
    telegram: 'https://t.me/Aartema_A',
    email: 'mailto:fs.artem.yurin@gmail.com',
    github: 'https://github.com/Br0No',
    linkedin: 'https://linkedin.com/in/artem-yurin-75b92b3ab/',
  },
  {
    name: 'Alina Khvorostian',
    position: 'Frontend Developer',
    descriptionKey: 'team.alina_khvorostian',
    initials: 'AK',
    gradient: 'from-rose-400 to-pink-600',
    telegram: 'https://t.me/',
    email: 'mailto:',
    github: 'https://github.com/',
    linkedin: 'https://linkedin.com/in/',
  },
  {
    name: 'Diana Kerekesha',
    position: 'Full-stack Developer',
    descriptionKey: 'team.diana_kerekesha',
    initials: 'DK',
    gradient: 'from-emerald-400 to-teal-600',
    telegram: 'https://t.me/',
    email: 'mailto:',
    github: 'https://github.com/',
    linkedin: 'https://linkedin.com/in/',
  },
  {
    name: 'Taras Demianuk',
    position: 'Full-stack Developer',
    descriptionKey: 'team.taras_demianuk',
    initials: 'TD',
    gradient: 'from-amber-400 to-orange-500',
    telegram: 'https://t.me/Demtar23',
    email: 'mailto:demtaras1@gmail.com',
    github: 'https://github.com/Demtar23',
    linkedin: 'https://linkedin.com/in/taras-demianuk/',
  },
];
